"""Adding columns to user table

Revision ID: 999609e80e23
Revises: 
Create Date: 2024-02-01 16:14:12.354787

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '999609e80e23'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('street', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('unit', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('city', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('state', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('zip', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('website', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('website')
        batch_op.drop_column('zip')
        batch_op.drop_column('state')
        batch_op.drop_column('city')
        batch_op.drop_column('unit')
        batch_op.drop_column('street')

    # ### end Alembic commands ###
